[font]
size = 20

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "buttonless"
opacity = 0.9

[keyboard]
bindings = [
	{ key = "Backspace", mods = "Control", action = "ToggleFullscreen" }
]

