[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "buttonless"
opacity = 0.98

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
	{ key = "Backspace", mods = "Control", action = "ToggleFullscreen" }
]
