"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[cmd_duration]
min_time = 100
format = 'underwent [$duration](bold yellow)'
